### ISSUE TITLE
Exporting Entities throws an exception

### ISSUE THREAD

**Issue by jellevervloessem** [MscrmTools/Javista.AttributesFactory#2]
Hi,

I try to export some entities from a solution and I get the following error:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Javista.AttributesFactory.AppCode.MetadataDocManager.ProcessDetails(AttributeMetadata amd, EntityMetadata emd, ExcelWorksheet sheet, Int32 line)
   at Javista.AttributesFactory.AppCode.MetadataDocManager.GenerateDocumentation(List`1 emds, String filePath, Boolean loadAllAttributes, BackgroundWorker worker)
   at Javista.AttributesFactory.PluginControl.tsbExportEntities_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
XrmToolBox
    Assembly Version: 1.2020.4.38
    Win32 Version: 1.2020.4.38
    CodeBase: file:///C:/XrmToolbox/XrmToolBox.exe
----------------------------------------
Javista.AttributesFactory
    Assembly Version: 1.2019.11.2
    Win32 Version: 1.2019.11.2
    CodeBase: file:///C:/USERS/JELLEVE/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.ATTRIBUTESFACTORY.DLL
```

**Comment by jellevervloessem** [comment]
It seems that this error only appears when selecting multiple entities. (I clicked teh Select All checkbox when exporting)

**Comment by MscrmTools** [comment]
The issue seems to be when there is a lookup field that points to an entity not included in the set of entities to export.
In this case, the relationship is not available in exported metadata.

I will fix this issue.

Thanks for reporting

**Comment by MscrmTools** [comment]
Can you test with this version ? It should avoid the error. Then in the Excel file, identify the Lookup that does not have any information about the relationship. 
Maybe you can find some extra information about why it wasn't able to find a relationship with `ReferencingAttribute`property equals the lookup attribute logicalname

[Javista.AttributesFactory.zip](https://github.com/MscrmTools/Javista.AttributesFactory/files/4580447/Javista.AttributesFactory.zip)

**Comment by MscrmTools** [comment]
@jellevervloessem were you able to test this?

**Comment by jellevervloessem** [comment]
Yes, I finally did. The error did not appear this time.
